# Generated by Django 5.2.5 on 2025-09-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_detailss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorphoto', models.ImageField(upload_to='')),
                ('doctorname', models.CharField(max_length=100)),
                ('doctoremail', models.CharField(max_length=100)),
                ('doctorphone', models.CharField(max_length=100)),
                ('doctorpayment', models.CharField(max_length=100)),
                ('doctorhours', models.CharField(max_length=100)),
                ('doctorspecialisation', models.CharField(max_length=100)),
            ],
        ),
    ]
