# Generated by Django 5.2.5 on 2025-09-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=100)),
                ('patient_age', models.CharField(max_length=100)),
                ('booking_date', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('patient_problem', models.CharField(max_length=1000)),
            ],
        ),
    ]
